SHOW DATABASES;
USE sqld_company;
SHOW TABLE STATUS;
SELECT * FROM DEPT;
SELECT * FROM EMP;

/*
JOIN
*/

# 예제1(WHERE절 JOIN)
SELECT EMPNO, ENAME, EMP.DEPTNO, DNAME    # DEPTNO 겹치니까 지정해줘야 함
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

# 예제1(INNER JOIN); USING/ON 정의 필수
SELECT EMPNO, ENAME, EMP.DEPTNO, DNAME FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

# 예제1(NATURAL JOIN); 동일 칼럼 자동 합쳐줌, USING/ON/WHERE 정의 불가, 테이블명 접두사 사용 불가
SELECT EMPNO, ENAME, DEPTNO, DNAME FROM EMP
NATURAL JOIN DEPT;

SELECT * FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;    # inner join은 공통 칼럼 두 번 출력, 원 테이블 순으로
SELECT * FROM EMP NATURAL JOIN DEPT;	# natural join은 공통 칼럼 한 번 맨 앞에다가 출력

# 예제2
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;
UPDATE DEPT_TEMP
SET DNAME = 'R&D' WHERE DNAME = 'RESEARCH';    # RESEARCH -> R&D
UPDATE DEPT_TEMP
SET DNAME = 'MARKETING' WHERE DNAME = 'SALES';    # MARKETING -> SALES
SELECT * FROM DEPT_TEMP;
SELECT * FROM DEPT JOIN DEPT_TEMP;    # 순서쌍 다 출력
SELECT * FROM DEPT NATURAL JOIN DEPT_TEMP;    # 값 일치하는 행만 출력

# 예제3
SELECT * FROM DEPT
JOIN DEPT_TEMP USING (DEPTNO);    # DEPTNO 칼럼만 한번 출력. USING도 접두사 사용 불가

# 예제4
SELECT * FROM DEPT
JOIN DEPT_TEMP USING (DNAME);    # DNAME 칼럼 중 데이터 같은 행만 출력, DNAME 맨 앞에 출력


# 70
USE sqld_excercises;

CREATE TABLE STADIUM (
STADIUM_ID CHAR(3) NOT NULL PRIMARY KEY,
STADIUM_NAME VARCHAR(40) NOT NULL);

CREATE TABLE TEAM (
TEAM_ID CHAR(3) NOT NULL PRIMARY KEY,
REGION_NAME VARCHAR(8) NOT NULL,
TEAM_NAME VARCHAR(40) NOT NULL,
STADIUM_ID CHAR(3) NOT NULL);

SELECT TEAM.REGION_NAME, TEAM.TEAM_NAME, TEAM.STADIUM_ID, STADIUM.STADIUM_NAME
FROM TEAM INNER JOIN STADIUM
ON (TEAM.STADIUM_ID = STADIUM.STADIUM_ID);

SELECT TEAM.REGION_NAME, TEAM.TEAM_NAME, TEAM.STADIUM_ID, STADIUM.STADIUM_NAME
FROM TEAM, STADIUM
WHERE TEAM.STADIUM_ID = STADIUM.STADIUM_ID;

SELECT T.REGION_NAME, T.TEAM_NAME, T.STADIUM_ID, S.STADIUM_NAME
FROM TEAM T INNER JOIN STADIUM S
WHERE T.STADIUM_ID = S.STADIUM_ID;

SELECT T.REGION_NAME, T.TEAM_NAME, T.STADIUM_ID, S.STADIUM_NAME
FROM TEAM T INNER JOIN STADIUM S
USING (T.STADIUM_ID = S.STADIUM_ID);    # 에러 => USING절은 조인 칼럼에 테이블명 사용 불가

SELECT T.REGION_NAME, T.TEAM_NAME, STADIUM_ID, S.STADIUM_NAME
FROM TEAM T INNER JOIN STADIUM S
USING (STADIUM_ID);    # 이렇게 하면 가능

